USE HW;
CREATE TABLE USERS(
    id  INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL 
);


CREATE TABLE WATCHLIST(
 id VARCHAR(255) PRIMARY KEY ,
 user_id INTEGER NOT NULL,
 content json
)